### ISSUE TITLE
When a Term is requested it will be filled within the begrepplist, we need a first screen.

### ISSUE THREAD

**Issue by dejmail** [dejmail/begrepptjanst#15]
When a Term is requested it will be filled within the begrepplist. This could be problematic since we dont have any verification that the ppl who request terms are valid. My suggestion is to set newly requested terms to "hidden" untill the backoffice have had time to verify the concepts. So we dont get alot of post from bots and immature teenagers.

_Originally posted by @trolibol in https://github.com/dejmail/begrepptjanst/issues/7#issuecomment-592382207_

**Comment by dejmail** [comment]
True, it could be a problem, but it might also be nice for users to see words that have been submitted, but that are not yet being worked on...is this just a difference in status ?

**Comment by trolibol** [comment]
Yeah its nice which we could build in the future but for now I believe that we should hide the requested term and then backoffice can set status "Working on". This to make sure SOKI/SMEES wont find alot of wierd terms.

**Comment by dejmail** [comment]
Ok we can do that, though I think the problem will be small. They'll be looking at the backend most of the day, almost everyday, so they can easily remove the dodgy entries.
