### ISSUE TITLE
Mobilanpassning

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#17]
Ser lite siså ut

**Comment by dejmail** [comment]
Vi behöver mycket mer information om vad är fel med mobilanpassning. Kan du skriver flera detaljer om vad specifikt är fel ? Såklart har vi inte använt mycket "class tags" för olika skärm storlek, så det är kanske en stor orsak.

**Comment by trolibol** [comment]
Den är ju till en början anpassad på ett bra sätt men när sökresultatet visas blir det lite vajsing :) Satte upp kommentaren för att inte glömma av det.
