### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#19]
As always, it _should be a quickfix_

suggestions: 

Vgrinformatik.se/olli (if we add more services in the future) 
vgrinformatik.se/

**Comment by dejmail** [comment]
It is a quick fix, we really only need to change the base url. Perhaps we should wait until after then end of next week though ?

**Comment by dejmail** [comment]
@trolibol - I think this is closed for the moment, we've changed it to begreppstjänst and changed the headers etc.
