### ISSUE TITLE
Suggestion: fix back button

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#23]
When a user uses the back button you leave our site, perhaps bind back button to landingpage. issue from Mats

**Comment by trolibol** [comment]
Veronika nämnde denna buggen den 24 april

**Comment by dejmail** [comment]
We need to fiddle with the HTML5 history API, and as all our users should be using more modern browsers, we don't have to support Internet Explorer. Look here for a good example...

http://html5doctor.com/history-api/
