### ISSUE TITLE
Kommentera begrepp

### ISSUE THREAD

**Issue by dejmail** [dejmail/begrepptjanst#33]
- Change the Ifrågasatt Begrepp table to Kommenterade Begrepp in the admin page
- Put more logic in the telefon screen so that the people sending in rubbish telefon numbers have to correct their number.

**Comment by dejmail** [comment]
- Changed the Ifrågasatt Begrepp table to Kommenterade Begrepp

**Comment by dejmail** [comment]
I think I should assign this to David, as he keeps adding 0 as a telephone number in the words he is ordering.

**Comment by davte1** [comment]
Hahah, well for customers not from the informatics team this is needs to be addressed. Otherwise it's to fill in the phonenumber for me since you've already got my number! ;)

**Comment by davte1** [comment]
Also i don't know how to adress the problem, the only thing I can do is to give you idea inputs...

**Comment by dejmail** [comment]
We've changed it so that one can put in their skype name or telefon number
