### ISSUE TITLE
David: Se till att hårdmarkerade ord har någon markering. 

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#35]
If a term is hardcoded it should be visual

**Comment by dejmail** [comment]
Could you expand this, I don't understand what this issue is about. Is it a bug, and improvement etc ?

**Comment by trolibol** [comment]
Lets say theres a term within Millenium thats hardcoded and cant be changed  David thought it would be great to keep track of them

**Comment by dejmail** [comment]
I think we can probably already do this if we have some sort of template of
how we capture the information. The external_register would be Cerner
Millenium, and then context beskrivning could contain that it was
hardcoded. Why would we need more ?
--
skype: liam_thompson
https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0x1C8D5FA7BF616A40

**Comment by davte1** [comment]
Yea my thought was just to add a column that had the name hardcoded/skåne or something. If we or another extern part want to adress this definition or add something they would get the information that it can't be changed without collaboration with skåne or cerner.
