### ISSUE TITLE
Från pelle: Status avrådd

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#42]
Termen ska bli genomstruken både i Olli och Olli admin samt gärna markeras med rosa bakgrundsfärg. Samma funktion över allt i Olli.
(Ska kunna visa avrådd term tillsammans med rekommenderad)

 Känner spontant att vi behöver prata med pelle igenom denna

**Comment by dejmail** [comment]
This is finished I think. We now having colouring in the partial results, the term definition and in the admin page. Simply applying colouring only to Avråds or Publicera ej looked a little strange, so I have added colouring to all the status types. Would be better if we could adjust the column width, as some of the status lengths are long.
