### ISSUE TITLE
Från pelle: minimera användandet av "övrig"

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#46]
Funktionen att Verifiera användning behöver revideras.
~~Fältet Kontext ska byta namn ”Verifierad användning”.~~
E-post behöver sparas för spårbarhet
Rubriken Välj arbetsström ändras till -
~~”Verifierar att begreppet används i:”~~
Lägg till ”Annat” i listan för val.
Visa fältet Annat för fritextinmatning när Annat är valt ovan.
Om möjligt komplettera listan ”Verifierar att …” med tillagda användare.

Dvs, om en användare inte hittar sin "härkomst"  ex kunskapsorganisationen så ska den sparas till nästa gång och då finnas i listan där man väljer. 

Behövs i mitt tycke någon typ av validering. 

Sentences that have a ~~line through them~~ can be considered finished.

**Comment by dejmail** [comment]
How are we going to save the email address ? Maybe instead of just saving an additional domain to to each begrepp as we do now, we actually have a table that saves part of the information
