### ISSUE TITLE
Take care of the "avrådda" synonyms

### ISSUE THREAD

**Issue by dejmail** [dejmail/begrepptjanst#5]
- We need to be able to show the status of the synonyms in some way, perhaps a button or icon next to it so that we can state which synonyms are "advised against"

**Comment by trolibol** [comment]
I think we should make all synonym to links and then refer the user to the (synonym)begrepp_förklaring

**Comment by dejmail** [comment]
Ok, so in the current "term_förklaring" table, we have synonyms, listed with their relevant statuses. Are you suggesting making them into HTTP links that refer directly to the definition that they are already coupled to ? Not sure I understand.
