### ISSUE TITLE
Fält för begreppsmodell, lista med möjliga val

### ISSUE THREAD

**Issue by PelleHadding** [dejmail/begrepptjanst#56]
Vi vill ha ett fält för att registrera av vilken modell som ett bergrepp tillhör/kan tillhöra. En envalslista med ett alternativ annan.

Fältet ska vara synlig på insidan och kan placeras mellan status och ID VGR.

**Comment by dejmail** [comment]
Vi kan skapa en tabell av olika Begrepp Informations Modeller, och så långt ni tar hand om innehållet där kan ni koppla begrepp och BIM. Låter det okej ?
