### ISSUE TITLE
when requesting a new term take ?=q = as predefined value so that the ordering a term form is prepopulated with the term

### ISSUE THREAD

**Issue by trolibol** [dejmail/begrepptjanst#58]

**Comment by dejmail** [comment]
Non comprendo amigo, what is the problem you're describing ?

**Comment by dejmail** [comment]
For this we need to change how we return the null 'begrepp' dictionary to the template page. If we don't have a term in the database, we send a null instantiation back, so what we should do instead is give the ajax a return variable and the Else a different return variable, and then update the template so it processes that correctly....line 197 in views.py. Then we can send the non-existing term back to the page function in base.py "populate_request_form()" to "populate_request_form(unknown_term)" or something similar
