### ISSUE TITLE
Change the focus of the window when a user clicks on a button so that the user does not need to scroll

### ISSUE THREAD

**Issue by dejmail** [dejmail/begrepptjanst#8]
https://jsfiddle.net/L56wxhqm/10/

**Comment by Louise1987** [comment]
I fix.

**Comment by trolibol** [comment]
I assume its just to print it in a different <div> and add some JS to it. Let me know if you need any help louise :)

**Comment by dejmail** [comment]
There could be different approaches here. I tried to change the fous of the element, but was unsuccessful. The first jsfiddle link was an example from Olle, it doesn't have to be implemented like that.

**Comment by dejmail** [comment]
Some thoughts

http://jtauber.com/blog/2008/04/28/auto-scrolling_is_jquery/
https://stackoverflow.com/questions/1433742/set-focus-to-field-in-dynamically-loaded-div

**Comment by dejmail** [comment]
This was fixed with some tweaking from MutationObserver, and using     div.scrollIntoView({behavior : 'smooth'}); to make the scrolling smooth.
